### ISSUE TITLE
[Feature request] Add automatic conversion of punycode domains

### ISSUE THREAD

**Issue by nwhisper2014** [james-stevens/powerdns-webui#60]
In the UI it is not easy to work with internationalized domains, because such domains are specified in punycode format ([RFC 3492](https://datatracker.ietf.org/doc/html/rfc3492)) and their names are not obvious. Every time I have to copy punycode into the converter to find out the original name of the domain.

I think it would be convenient if for such domains to add its original name immediately below the punycode name in a small font. Or as a floating message when you hover your mouse cursor...

Perhaps this link will be useful as a starting point: https://github.com/mathiasbynens/punycode.js

**Comment by nwhisper2014** [comment]
For example:

The internalized domain "платиновая-унция.рф." in punycode encoding looks like "xn----7sbah3adpsdgg2bt7b1if.xn--p1ai."  Such names are impossible to understand without a converter...

**Comment by james-stevens** [comment]
yeah - adding in some options to convert & tool-tips to show the UTF-8 should be pretty easy

I do a lot of work in Handshake, which is a blockchain replacement for the ROOT zone & emoji domain names, including as TLDs, are really popular there. If you've not heard of it you should take a look :)

**Comment by james-stevens** [comment]
If you pull the `dev` branch, it now has some automatic punycode conversion using the `punycode.js` module you suggested.

All record & zone names are still displayed as punycode, but the IDN version will appear as a `tool-tip` when you hover the mouse over the name - for both zones & record names.

In the `Add Host` (now called `Add Record`) function, the `Name` edit box now allows you to directly enter IDN names, which will be automatically converted to punycode. Renaming a host & creating a zone also supports automatic IDN->punycode conversion (only the zone name, but the `NS` names).

If the `punycode.js` file is missing these features should silently no longer work, but everything else should be OK.

Let me know how this works for you & if you want / recommend any changes.

*Technically* IDN names (full 8-bit names) can actually be used directly in DNS these days - If people are doing this, it might be confusing if I simply (& silently) automatically display punycode names as IDN names (instead of as tooltips), but I could easily do this & (for example) make them **bold** to show they are a converted name??

Although making names bold probably wouldn't work too well for emoji names !!

As all my hostname are ascii, it's hard to know what works best.

**Comment by james-stevens** [comment]
When you've had a chance to look at this, let me know & I'll either make more changes or just merge `dev` into `master`

**Comment by nwhisper2014** [comment]
Displaying IDNs in the tooltip is, in my opinion, convenient if there are few domains in punycode. If there are more than a dozen of such domains, it becomes difficult to visually search for the right name.

Perhaps it would be correct to display such domains only as IDN names? Or try to display in this format:

`xn--puni.code.xn--demo [idn.name]`

In my opinion, change the way domain names are displayed only in the general list of domains. For edit mode, the current way of displaying, when the IDN appears in the tooltip, is fine. But if you add IDN next to it in brackets, that would be good too.

**Bold**, I think, is not necessary.

**Comment by james-stevens** [comment]
OK - I pushed a new commit to `dev` - now, in the zones list & the record list, there is an extra column to show the IDN, but only if the zone name or record name is punycode

In the records list, it will only show the IDN if the **record** name is IDN - so an ascii record name in an IDN zone will not show as IDN - otherwise every single record name would show as IDN.

The tooltips remain exactly as before.

I've also merged the `punycode.js` file into the `index.html` file - so back to one file :)

**Comment by james-stevens** [comment]
I just pushed another commit to `dev` - it now has a look & feel that kinda emulates github, but in blue

Should be pretty easy to change the colour scheme to create a `light` and `dark` theme now

I probably won't support "themes" as such, but just provide different `css` files and let the user change it if they wish (with some instructions)

Def looks a bit more modern!

**Comment by nwhisper2014** [comment]
The IDNs in the extra column look good :) Thank you! That's what I've been missing :)

The design changes have freshened up the interface a bit, that's great.
I agree, you don't need to drastically change the design, it might increase the file size and complicate the code.

I'm not sure about the need to support external CSS files. I think adding 2 or 3 color schemes (dark, light and pretty :) ) would be enough. If someone needs to change the color scheme, they can easily do it by editing the file.

I like that such a very complex product fits into just one html file, while still being usable and fast :)

**Comment by james-stevens** [comment]
yeah, I like it being all in one file - it makes deploying it & sending it to ppl much easier :)

OK - just pushed an update (to `dev`) - it now has theme support (including saving your preferred theme in the cookies), comes with Blue, Red, Light & Dark - the default is Blue.

Light & Dark are mostly a copy of the github look & feel - Red is the same as Blue, but tinted red instead of blue.

When you look at the code you'll see, its *really* easy to change the colours if you want, or even add your own colour scheme.

When you first load the page there is a very slight glitch as it will initially load with no CSS before it reads the cookies & sets your preferred theme (or the default theme) - I could easily get it to set a default theme first, but there's still going to be a glitch when it switches from default to your preferred - so as the glitch is very very slight, I'm going to leave it like this for now

I've also changed the zone name & record name in the top bar to be hyperlinked text instead of buttons, to indicate they are data values, rather than names of functions
